//! Checks of the environment a TUN gateway runs in.
//!
//! Docker's embedded DNS server (`127.0.0.11`, on user-defined networks)
//! forwards names it does not know to upstream servers. Upstreams inherited from
//! the host's `resolv.conf` are queried **from the host's network namespace**:
//! those queries never enter this namespace's TUN device, so apps behind the
//! gateway get real addresses from the host's resolver instead of mihomo's
//! fake-ip (their lookups leak and domain rules stop matching). Upstreams set
//! explicitly (`dns:` in compose, `--dns`) are queried from the container's own
//! namespace, where mihomo hijacks them, and still work while mihomo is down.
//!
//! Docker records which case applies in a comment of the generated file:
//! `# ExtServers: [host(192.168.0.1)]` versus `# ExtServers: [1.1.1.1]`.

use std::io::Read;

const RESOLV_CONF: &str = "/etc/resolv.conf";

/// Upstream servers Docker's embedded DNS reaches from the host's namespace,
/// as listed in `resolv_conf`, or `None` when DNS stays in this namespace.
pub fn docker_dns_via_host(resolv_conf: &str) -> Option<String> {
    let servers = resolv_conf
        .lines()
        .find_map(|line| line.strip_prefix("# ExtServers:"))?
        .trim();
    servers
        .contains("host(")
        .then(|| crate::util::sanitize(servers))
}

/// A warning when app DNS would bypass the tunnel (see the module docs).
pub fn dns_warning() -> Option<String> {
    let mut text = String::new();
    std::fs::File::open(RESOLV_CONF)
        .ok()?
        .take(64 * 1024)
        .read_to_string(&mut text)
        .ok()?;
    docker_dns_via_host(&text).map(|servers| {
        format!(
            "Docker resolves names for this container through the host's resolver \
             {servers}, outside the tunnel: apps get real addresses and their DNS \
             lookups leak. Give the gateway an explicit DNS server (compose: \
             `dns: [1.1.1.1]`, docker run: `--dns 1.1.1.1`); see docs/DOCKER.md"
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = "# Generated by Docker Engine.\n\nnameserver 127.0.0.11\n\
                          options ndots:0\n\n# Based on host file: '/etc/resolv.conf' \
                          (internal resolver)\n";

    #[test]
    fn host_namespace_upstreams_are_detected() {
        let via_host = format!("{HEADER}# ExtServers: [host(192.168.0.1)]\n# Overrides: []\n");
        assert_eq!(
            docker_dns_via_host(&via_host).as_deref(),
            Some("[host(192.168.0.1)]")
        );
        let loopback = format!("{HEADER}# ExtServers: [host(127.0.0.53)]\n");
        assert!(docker_dns_via_host(&loopback).is_some());
    }

    #[test]
    fn explicit_upstreams_and_plain_files_are_fine() {
        let explicit =
            format!("{HEADER}# ExtServers: [1.1.1.1 8.8.8.8]\n# Overrides: [nameservers]\n");
        assert_eq!(docker_dns_via_host(&explicit), None);
        // Default bridge network: the host's servers are copied, no embedded DNS.
        let legacy =
            "nameserver 192.168.0.1\n\n# Based on host file: '/etc/resolv.conf' (legacy)\n";
        assert_eq!(docker_dns_via_host(legacy), None);
        assert_eq!(docker_dns_via_host("nameserver 1.1.1.1\n"), None);
    }
}
